# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kek.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 650)
        MainWindow.setMinimumSize(QtCore.QSize(460, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setAccessibleName("")
        self.tab_log.setObjectName("tab_log")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_log)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_log)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setItemsExpandable(False)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 7, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_log)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 2, 1, 1)
        self.team1 = QtWidgets.QTableWidget(self.tab_log)
        self.team1.setMinimumSize(QtCore.QSize(430, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.team1.setFont(font)
        self.team1.setMouseTracking(True)
        self.team1.setToolTip("")
        self.team1.setToolTipDuration(12)
        self.team1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.team1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.team1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.team1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.team1.setDragDropOverwriteMode(False)
        self.team1.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.team1.setShowGrid(True)
        self.team1.setCornerButtonEnabled(False)
        self.team1.setObjectName("team1")
        self.team1.setColumnCount(0)
        self.team1.setRowCount(0)
        self.team1.horizontalHeader().setDefaultSectionSize(80)
        self.team1.horizontalHeader().setMinimumSectionSize(20)
        self.team1.horizontalHeader().setStretchLastSection(False)
        self.team1.verticalHeader().setVisible(True)
        self.team1.verticalHeader().setDefaultSectionSize(20)
        self.team1.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.team1, 3, 2, 1, 1)
        self.team2 = QtWidgets.QTableWidget(self.tab_log)
        self.team2.setMinimumSize(QtCore.QSize(430, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.team2.setFont(font)
        self.team2.setMouseTracking(True)
        self.team2.setToolTip("")
        self.team2.setToolTipDuration(12)
        self.team2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.team2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.team2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.team2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.team2.setDragDropOverwriteMode(False)
        self.team2.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.team2.setShowGrid(True)
        self.team2.setCornerButtonEnabled(False)
        self.team2.setObjectName("team2")
        self.team2.setColumnCount(0)
        self.team2.setRowCount(0)
        self.team2.horizontalHeader().setDefaultSectionSize(80)
        self.team2.horizontalHeader().setMinimumSectionSize(20)
        self.team2.horizontalHeader().setStretchLastSection(False)
        self.team2.verticalHeader().setVisible(True)
        self.team2.verticalHeader().setDefaultSectionSize(20)
        self.team2.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.team2, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_log)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_log)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_log)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 7, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_log)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 2, 1, 3)
        self.compare = QtWidgets.QTableWidget(self.tab_log)
        self.compare.setMaximumSize(QtCore.QSize(250, 16777215))
        self.compare.setObjectName("compare")
        self.compare.setColumnCount(0)
        self.compare.setRowCount(0)
        self.gridLayout_2.addWidget(self.compare, 2, 4, 5, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 6, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_log)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 4, 1, 1)
        self.label.raise_()
        self.comboBox.raise_()
        self.team2.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.line_2.raise_()
        self.team1.raise_()
        self.treeWidget.raise_()
        self.compare.raise_()
        self.line_4.raise_()
        self.tabWidget.addTab(self.tab_log, "")
        self.tab_player = QtWidgets.QWidget()
        self.tab_player.setObjectName("tab_player")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_player)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_stat = QtWidgets.QTableWidget(self.tab_player)
        self.table_stat.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_stat.setObjectName("table_stat")
        self.table_stat.setColumnCount(0)
        self.table_stat.setRowCount(0)
        self.table_stat.horizontalHeader().setSortIndicatorShown(False)
        self.table_stat.verticalHeader().setDefaultSectionSize(20)
        self.table_stat.verticalHeader().setHighlightSections(True)
        self.table_stat.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_3.addWidget(self.table_stat, 4, 0, 1, 7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 5, 3, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 0, 3, 3, 1)
        self.line_player3 = QtWidgets.QLineEdit(self.tab_player)
        self.line_player3.setObjectName("line_player3")
        self.gridLayout_3.addWidget(self.line_player3, 1, 4, 1, 1)
        self.line_player4 = QtWidgets.QLineEdit(self.tab_player)
        self.line_player4.setObjectName("line_player4")
        self.gridLayout_3.addWidget(self.line_player4, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_player)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_player)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_player)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 3, 0, 1, 7)
        self.label_4 = QtWidgets.QLabel(self.tab_player)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.line_player1 = QtWidgets.QLineEdit(self.tab_player)
        self.line_player1.setObjectName("line_player1")
        self.gridLayout_3.addWidget(self.line_player1, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 3, 1)
        self.line_player2 = QtWidgets.QLineEdit(self.tab_player)
        self.line_player2.setObjectName("line_player2")
        self.gridLayout_3.addWidget(self.line_player2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_player)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_player, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.parts_have = QtWidgets.QTableWidget(self.groupBox_3)
        self.parts_have.setShowGrid(True)
        self.parts_have.setGridStyle(QtCore.Qt.SolidLine)
        self.parts_have.setObjectName("parts_have")
        self.parts_have.setColumnCount(0)
        self.parts_have.setRowCount(0)
        self.parts_have.horizontalHeader().setVisible(False)
        self.parts_have.horizontalHeader().setDefaultSectionSize(50)
        self.parts_have.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_8.addWidget(self.parts_have, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.materials_need = QtWidgets.QTableWidget(self.groupBox_4)
        self.materials_need.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.materials_need.setShowGrid(True)
        self.materials_need.setGridStyle(QtCore.Qt.SolidLine)
        self.materials_need.setObjectName("materials_need")
        self.materials_need.setColumnCount(0)
        self.materials_need.setRowCount(0)
        self.materials_need.horizontalHeader().setVisible(False)
        self.materials_need.horizontalHeader().setDefaultSectionSize(50)
        self.materials_need.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_6.addWidget(self.materials_need, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.materials_have = QtWidgets.QTableWidget(self.groupBox_2)
        self.materials_have.setShowGrid(True)
        self.materials_have.setGridStyle(QtCore.Qt.SolidLine)
        self.materials_have.setObjectName("materials_have")
        self.materials_have.setColumnCount(0)
        self.materials_have.setRowCount(0)
        self.materials_have.horizontalHeader().setVisible(False)
        self.materials_have.horizontalHeader().setDefaultSectionSize(50)
        self.materials_have.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_7.addWidget(self.materials_have, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.parts_need = QtWidgets.QTableWidget(self.groupBox_5)
        self.parts_need.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.parts_need.setShowGrid(True)
        self.parts_need.setGridStyle(QtCore.Qt.SolidLine)
        self.parts_need.setObjectName("parts_need")
        self.parts_need.setColumnCount(0)
        self.parts_need.setRowCount(0)
        self.parts_need.horizontalHeader().setVisible(False)
        self.parts_need.horizontalHeader().setDefaultSectionSize(50)
        self.parts_need.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_5.addWidget(self.parts_need, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.fed_s = QtWidgets.QCheckBox(self.groupBox_7)
        self.fed_s.setObjectName("fed_s")
        self.gridLayout_11.addWidget(self.fed_s, 0, 1, 1, 1)
        self.jericho_l = QtWidgets.QCheckBox(self.groupBox_7)
        self.jericho_l.setObjectName("jericho_l")
        self.gridLayout_11.addWidget(self.jericho_l, 2, 2, 1, 1)
        self.jericho_m = QtWidgets.QCheckBox(self.groupBox_7)
        self.jericho_m.setObjectName("jericho_m")
        self.gridLayout_11.addWidget(self.jericho_m, 1, 2, 1, 1)
        self.fed_m = QtWidgets.QCheckBox(self.groupBox_7)
        self.fed_m.setObjectName("fed_m")
        self.gridLayout_11.addWidget(self.fed_m, 1, 1, 1, 1)
        self.empire_l = QtWidgets.QCheckBox(self.groupBox_7)
        self.empire_l.setObjectName("empire_l")
        self.gridLayout_11.addWidget(self.empire_l, 2, 0, 1, 1)
        self.fed_l = QtWidgets.QCheckBox(self.groupBox_7)
        self.fed_l.setObjectName("fed_l")
        self.gridLayout_11.addWidget(self.fed_l, 2, 1, 1, 1)
        self.empire_s = QtWidgets.QCheckBox(self.groupBox_7)
        self.empire_s.setObjectName("empire_s")
        self.gridLayout_11.addWidget(self.empire_s, 0, 0, 1, 1)
        self.empire_m = QtWidgets.QCheckBox(self.groupBox_7)
        self.empire_m.setObjectName("empire_m")
        self.gridLayout_11.addWidget(self.empire_m, 1, 0, 1, 1)
        self.jericho_s = QtWidgets.QCheckBox(self.groupBox_7)
        self.jericho_s.setObjectName("jericho_s")
        self.gridLayout_11.addWidget(self.jericho_s, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_7, 1, 0, 1, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.empire_11 = QtWidgets.QCheckBox(self.groupBox_8)
        self.empire_11.setObjectName("empire_11")
        self.gridLayout_12.addWidget(self.empire_11, 1, 0, 1, 1)
        self.empire_14 = QtWidgets.QCheckBox(self.groupBox_8)
        self.empire_14.setObjectName("empire_14")
        self.gridLayout_12.addWidget(self.empire_14, 2, 0, 1, 1)
        self.fed_8 = QtWidgets.QCheckBox(self.groupBox_8)
        self.fed_8.setObjectName("fed_8")
        self.gridLayout_12.addWidget(self.fed_8, 0, 1, 1, 1)
        self.jericho_8 = QtWidgets.QCheckBox(self.groupBox_8)
        self.jericho_8.setObjectName("jericho_8")
        self.gridLayout_12.addWidget(self.jericho_8, 0, 2, 1, 1)
        self.fed_11 = QtWidgets.QCheckBox(self.groupBox_8)
        self.fed_11.setObjectName("fed_11")
        self.gridLayout_12.addWidget(self.fed_11, 1, 1, 1, 1)
        self.jericho_14 = QtWidgets.QCheckBox(self.groupBox_8)
        self.jericho_14.setObjectName("jericho_14")
        self.gridLayout_12.addWidget(self.jericho_14, 2, 2, 1, 1)
        self.empire_8 = QtWidgets.QCheckBox(self.groupBox_8)
        self.empire_8.setObjectName("empire_8")
        self.gridLayout_12.addWidget(self.empire_8, 0, 0, 1, 1)
        self.fed_14 = QtWidgets.QCheckBox(self.groupBox_8)
        self.fed_14.setObjectName("fed_14")
        self.gridLayout_12.addWidget(self.fed_14, 2, 1, 1, 1)
        self.jericho_11 = QtWidgets.QCheckBox(self.groupBox_8)
        self.jericho_11.setObjectName("jericho_11")
        self.gridLayout_12.addWidget(self.jericho_11, 1, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_8, 2, 0, 3, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.spiral = QtWidgets.QCheckBox(self.groupBox_9)
        self.spiral.setObjectName("spiral")
        self.gridLayout_13.addWidget(self.spiral, 0, 0, 1, 1)
        self.check_all = QtWidgets.QPushButton(self.groupBox_9)
        self.check_all.setObjectName("check_all")
        self.gridLayout_13.addWidget(self.check_all, 4, 0, 1, 1)
        self.dart = QtWidgets.QCheckBox(self.groupBox_9)
        self.dart.setObjectName("dart")
        self.gridLayout_13.addWidget(self.dart, 3, 0, 1, 1)
        self.ende = QtWidgets.QCheckBox(self.groupBox_9)
        self.ende.setObjectName("ende")
        self.gridLayout_13.addWidget(self.ende, 1, 0, 1, 1)
        self.uncheck_all = QtWidgets.QPushButton(self.groupBox_9)
        self.uncheck_all.setObjectName("uncheck_all")
        self.gridLayout_13.addWidget(self.uncheck_all, 5, 0, 1, 1)
        self.garg = QtWidgets.QCheckBox(self.groupBox_9)
        self.garg.setObjectName("garg")
        self.gridLayout_13.addWidget(self.garg, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_9, 1, 2, 4, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.progress = QtWidgets.QTableWidget(self.groupBox_6)
        self.progress.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.progress.setShowGrid(True)
        self.progress.setGridStyle(QtCore.Qt.SolidLine)
        self.progress.setObjectName("progress")
        self.progress.setColumnCount(0)
        self.progress.setRowCount(0)
        self.progress.horizontalHeader().setVisible(False)
        self.progress.horizontalHeader().setDefaultSectionSize(50)
        self.progress.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_10.addWidget(self.progress, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.open_file = QtWidgets.QAction(MainWindow)
        self.open_file.setObjectName("open_file")
        self.exit_btn = QtWidgets.QAction(MainWindow)
        self.exit_btn.setObjectName("exit_btn")
        self.actionOne = QtWidgets.QAction(MainWindow)
        self.actionOne.setObjectName("actionOne")
        self.actionDsadas = QtWidgets.QAction(MainWindow)
        self.actionDsadas.setObjectName("actionDsadas")
        self.menuOpen.addAction(self.open_file)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.exit_btn)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "read dem logs - by Tillo"))
        self.team1.setSortingEnabled(False)
        self.team2.setSortingEnabled(False)
        self.label.setText(_translate("MainWindow", "Team 2"))
        self.label_2.setText(_translate("MainWindow", "Team 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), _translate("MainWindow", "Log reader"))
        self.table_stat.setSortingEnabled(False)
        self.label_5.setText(_translate("MainWindow", "Player 3"))
        self.label_6.setText(_translate("MainWindow", "Player 4"))
        self.label_4.setText(_translate("MainWindow", "Player 2"))
        self.label_3.setText(_translate("MainWindow", "Player 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_player), _translate("MainWindow", "Compare players"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Parts you have"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Materials you need"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Materials you have"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Parts you need"))
        self.groupBox.setTitle(_translate("MainWindow", "Ships"))
        self.groupBox_7.setTitle(_translate("MainWindow", "R15 Craftables"))
        self.fed_s.setText(_translate("MainWindow", "Peregrine"))
        self.jericho_l.setText(_translate("MainWindow", "Ronin"))
        self.jericho_m.setText(_translate("MainWindow", "Saw One"))
        self.fed_m.setText(_translate("MainWindow", "Jaguar"))
        self.empire_l.setText(_translate("MainWindow", "Kraken"))
        self.fed_l.setText(_translate("MainWindow", "Octopus"))
        self.empire_s.setText(_translate("MainWindow", "Cyning"))
        self.empire_m.setText(_translate("MainWindow", "Mjolnir"))
        self.jericho_s.setText(_translate("MainWindow", "Caltrop"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Dessies"))
        self.empire_11.setText(_translate("MainWindow", "Brave"))
        self.empire_14.setText(_translate("MainWindow", "Vigilant"))
        self.fed_8.setText(_translate("MainWindow", "Procyon"))
        self.jericho_8.setText(_translate("MainWindow", "Archon"))
        self.fed_11.setText(_translate("MainWindow", "Antares"))
        self.jericho_14.setText(_translate("MainWindow", "Tyrant"))
        self.empire_8.setText(_translate("MainWindow", "Invincible"))
        self.fed_14.setText(_translate("MainWindow", "Sirius"))
        self.jericho_11.setText(_translate("MainWindow", "Sibyl"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Random"))
        self.spiral.setText(_translate("MainWindow", "Spiral"))
        self.check_all.setText(_translate("MainWindow", "check all"))
        self.dart.setText(_translate("MainWindow", "Dart"))
        self.ende.setText(_translate("MainWindow", "Endeavour"))
        self.uncheck_all.setText(_translate("MainWindow", "uncheck all"))
        self.garg.setText(_translate("MainWindow", "Gargoyle"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Progress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ship parts"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.open_file.setText(_translate("MainWindow", "Open"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.actionOne.setText(_translate("MainWindow", "one"))
        self.actionDsadas.setText(_translate("MainWindow", "dsadas"))

